### ISSUE TITLE
Unable to run Edit Software Sources from Pop!_Shop

### ISSUE THREAD

**Issue by kc4dej** [pop-os/repolib#25]
**Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop - Edit Software Sources

**Issue/Bug Description:**
I try to open Edit Software Sources but when I click on the Edit Software Sources icon, the wheel spins and then stops.

**Steps to reproduce (if you know):**
I click on the Edit Software Sources icon, the wheel spins and then stops.

**Expected behavior:**
Open software sources

**Other Notes:**
I just upgraded from 19.10 to 20.10

Running Repoman from terminal gives the following:
<pre>(repoman:8883): Gtk-<font color="#75507B"><b>CRITICAL</b></font> **: <font color="#3465A4">08:42:20.952</font>: gtk_widget_grab_default: assertion &apos;gtk_widget_get_can_default (widget)&apos; failed
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/repoman/main.py&quot;, line 37, in do_activate
    self.win = Window()
  File &quot;/usr/lib/python3/dist-packages/repoman/window.py&quot;, line 36, in __init__
    self.stack = Stack(self)
  File &quot;/usr/lib/python3/dist-packages/repoman/stack.py&quot;, line 58, in __init__
    self.list_all = List(self)
  File &quot;/usr/lib/python3/dist-packages/repoman/list.py&quot;, line 134, in __init__
    self.generate_entries()
  File &quot;/usr/lib/python3/dist-packages/repoman/list.py&quot;, line 211, in generate_entries
    self.sources = repo.get_all_sources()
  File &quot;/usr/lib/python3/dist-packages/repoman/repo.py&quot;, line 157, in get_all_sources
    source.load_from_file()
  File &quot;/usr/lib/python3/dist-packages/repolib/legacy_deb.py&quot;, line 134, in load_from_file
    self.load_from_sources()
  File &quot;/usr/lib/python3/dist-packages/repolib/legacy_deb.py&quot;, line 110, in load_from_sources
    self.make_names()
  File &quot;/usr/lib/python3/dist-packages/repolib/legacy_deb.py&quot;, line 80, in make_names
    self.name = self.sources[0].make_</pre>

**Comment by isantop** [comment]
I believe this is the same issue @ahoneybun pointed out in #24 and will be fixed by that PR. Most likely there is an ftp, file, or other schema in one of the source list files.

**Comment by brs17** [comment]
Why does insufficient sources validation cause a graphical tool to fail to launch? Shouldn't repoman launch regardless if there are any valid sources set up?

**Comment by brs17** [comment]
I am now on version `1.4.0~1603733612~20.10~f30cddb` (this commit appears to be the one including pr #24 ) of python3-repolib and still get the same issue when attempting to launch repoman from either Pop!_Shop or directly from the command line `repoman`.

**Comment by isantop** [comment]
@brs17 can you send over the output you're getting from `repoman debug` as well as `apt-manage -bb`

**Comment by kc4dej** [comment]
This was fixed today by a system update. Thanks to whoever fixed it!

**Comment by brs17** [comment]
I can confirm that updating from `1.4.0~1603733612~20.10~f30cddb` to `1.4.0~1603811627~20.10~edd989f` seems to have resolved the issue.
