### ISSUE TITLE
CI failing due to bionic build

### ISSUE THREAD

**Issue by ids1024** [pop-os/repolib#34]
The build failure on bionic seems to be in `PPATestCase.test_suite()`, and caused by https://github.com/pop-os/repolib/commit/0f74753092eddbb64af129cd983162a2413f7ce0:

```
    def test_suite(self):
>       self.assertEqual(self.source.suites, [util.DISTRO_CODENAME])
E       AssertionError: Lists differ: ['Bionic', 'Beaver'] != ['Bionic Beaver']
E       
E       First differing element 0:
E       'Bionic'
E       'Bionic Beaver'
E       
E       First list contains 1 additional elements.
E       First extra element 1:
E       'Beaver'
E       
E       - ['Bionic', 'Beaver']
E       ?         ^^^^
E       
E       + ['Bionic Beaver']
E       ?         
```

I'm not sure if we're concerned about packaging this for Bionic. But if so, the build failure should probably be fixed. If not, Bionic builds should probably be disabled by adding a `master_bionic` branch without a `debian` directory.

**Comment by isantop** [comment]
We currently have a master_bionic branch which does not build. Any failures on Bionic (e.g. for PRs) can be safely ignored.
