### ISSUE TITLE
[22.04] updates and upgrades failing on `python3-repolib` package

### ISSUE THREAD

**Issue by wagnerck** [pop-os/repolib#42]
We're seeing a number of customer systems that have had failed update and/or upgrade attempts since Friday. Customer systems are sometimes ending up in a half-upgraded state where the system boots but many things are broken. It's unclear what the root cause is.

This may be related to the commit that was merged on Thursday (https://github.com/pop-os/repolib/commit/e2261d9cb849ca776b6435448a6cb89be31fc62e) but I'm not really seeing how it could cause the issue, unless it triggered something in an earlier commit.

Customers are seeing something like this when running `apt full-upgrade`:
```
Setting up python3-repolib (1.5.2~1651157034~22.04~e2261d9) ...
ln: failed to create symbolic link '/usr/bin/add-apt-repository': File exists
ln: failed to create symbolic link '/usr/bin/apt-add-repository': File exists
dpkg: error processing package python3-repolib (--configure):
installed python3-repolib package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
python3-repolib
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
`/usr/bin/apt-add-repository` is provided by the `software-properties-common` package from Ubuntu, and on a default system it is _not_ symlinked to `/usr/lib/repolib/add-apt-repository`, which is provided by our own `python3-repolib`. This output is from a fresh VM that was installed with v21.10 and then upgraded to v22.04, which failed to replicate the problem:
```
ckw@pop-os:~$ ls -la /usr/lib/repolib/add-apt-repository
-rwxr-xr-x 1 root root 4650 Apr 28 09:43 /usr/lib/repolib/add-apt-repository
ckw@pop-os:~$ ls -la /usr/bin/add-apt-repository
-rwxr-xr-x 1 root root 14478 Apr  1 13:48 /usr/bin/add-apt-repository
```
Here are some public threads on Ubuntu forums and Reddit:
https://askubuntu.com/questions/1405650/cannot-upgrade-any-applications-python3-repolib-error-pop-os
https://www.reddit.com/r/pop_os/comments/uff16m/unable_to_update_packages_post_2204_upgrade/
https://www.reddit.com/r/pop_os/comments/ues9ru/updating_error_2204/

Users have reported various fixes but they all seem like workarounds which might lead to further package problems later. For example:
```
I have fixed the error I was getting.
  "Setting up python3-repolib (1.5.2~1651157034~22.04~e2261d9) ...
ln: failed to create symbolic link '/usr/bin/add-apt-repository': File exists"

I went into the directory /usr/bin/ and deleted the file @add-apt-repository.
After I deleted the file Pop Shop updates are working now.
```

**Comment by jacobgkau** [comment]
@isantop Should the `python3-repolib` package be conflicting with `software-properties-common`?

**Comment by isantop** [comment]
@jacobgkau I don't think that's necessary; the preinst and prerm scripts should be handling these situations correctly. We're providing the `add-apt-repository` script currently only if it isn't being provided by Software Properties. The preinst script was simply not correctly set up to manage its symlinks correctly.

**Comment by jacobgkau** [comment]
> I don't think that's necessary; the preinst and prerm scripts should be handling these situations correctly. We're providing the `add-apt-repository` script currently only if it isn't being provided by Software Properties.

Does the `software-properties-common` version of the script have any advantages over the one that repolib provides? The message in our version of `add-apt-repository` states that the command is deprecated and suggests using `apt-manage` instead; I'm not sure why having `software-properties-common` installed would change that deprecation (or why we'd be providing our own `add-apt-repository` script at all if we don't see any issue with people using the one from `software-properties-common` instead.) This doesn't seem like it makes semantic sense, aside from the implementation issues (also asked in https://github.com/pop-os/repolib/pull/43 about the situation of having `software-properties-common` installed when `python3-repolib` is configured but them removing `software-properties-common` after.)

**Comment by snarky-puppy** [comment]
apt upgrade failed on me today, the postinst script is not correctly matching the current state of software-properties-common:

```
$ dpkg -s software-properties-common | grep 'Status'
Status: deinstall ok config-files

$ head /var/lib/dpkg/info/python3-repolib.postinst
#!/bin/bash

## Provide a replacement for the add-apt-repository command 
if [[ `dpkg -s software-properties-common | grep 'Status'` != *'installed'* ]]; then 
    ln -s /usr/lib/repolib/add-apt-repository /usr/bin/add-apt-repository
    ln -s /usr/lib/repolib/add-apt-repository /usr/bin/apt-add-repository
```

This was the state of my machine after having previously used the PopOS GUI to do a dist upgrade. My hacky fix was to delete the links and continue the upgrade.

**Comment by wagnerck** [comment]
@snarky-puppy Removing the two symlinks is in fact the workaround that we're giving users right now. In some cases we are also recommending that users install the `software-properties-common` package before continuing the system upgade, as the fixes to the `python3-repolib` scripts are still being worked on, since having that package installed as well prevents the current version of `python3-repolb`'s scripts from misbehaving.
