### ISSUE TITLE
Install Works KeyError: 'list'

### ISSUE THREAD

**Issue by wriver4** [pop-os/repolib#64]
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)

Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
Cloning into 'repolib'...
remote: Enumerating objects: 567, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 567 (delta 71), reused 55 (delta 25), pack-reused 445
Receiving objects: 100% (567/567), 141.83 KiB | 5.25 MiB/s, done.
Resolving deltas: 100% (353/353), done.

apt install python3-all python3-setuptools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-setuptools is already the newest version (59.6.0-1.2).
python3-all is already the newest version (3.10.6-1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

cd repolib
repolib# python3 ./setup.py install
/root/repolib/./setup.py:31: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/repolib
copying repolib/deb.py -> build/lib/repolib
copying repolib/system_test.py -> build/lib/repolib
copying repolib/system.py -> build/lib/repolib
copying repolib/source.py -> build/lib/repolib
copying repolib/__version__.py -> build/lib/repolib
copying repolib/util.py -> build/lib/repolib
copying repolib/legacy_deb_test.py -> build/lib/repolib
copying repolib/ppa.py -> build/lib/repolib
copying repolib/legacy_deb.py -> build/lib/repolib
copying repolib/source_test.py -> build/lib/repolib
copying repolib/deb_test.py -> build/lib/repolib
copying repolib/ppa_test.py -> build/lib/repolib
copying repolib/__init__.py -> build/lib/repolib
creating build/lib/repolib/command
copying repolib/command/add.py -> build/lib/repolib/command
copying repolib/command/argparser.py -> build/lib/repolib/command
copying repolib/command/command.py -> build/lib/repolib/command
copying repolib/command/__init__.py -> build/lib/repolib/command
running build_scripts
creating build/scripts-3.10
copying and adjusting bin/apt-manage -> build/scripts-3.10
changing mode of build/scripts-3.10/apt-manage from 644 to 755
running install_lib
creating /usr/local/lib/python3.10/dist-packages/repolib
creating /usr/local/lib/python3.10/dist-packages/repolib/command
copying build/lib/repolib/command/add.py -> /usr/local/lib/python3.10/dist-packages/repolib/command
copying build/lib/repolib/command/argparser.py -> /usr/local/lib/python3.10/dist-packages/repolib/command
copying build/lib/repolib/command/command.py -> /usr/local/lib/python3.10/dist-packages/repolib/command
copying build/lib/repolib/command/__init__.py -> /usr/local/lib/python3.10/dist-packages/repolib/command
copying build/lib/repolib/deb.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/system_test.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/system.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/source.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/__version__.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/util.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/legacy_deb_test.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/ppa.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/legacy_deb.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/source_test.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/deb_test.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/ppa_test.py -> /usr/local/lib/python3.10/dist-packages/repolib
copying build/lib/repolib/__init__.py -> /usr/local/lib/python3.10/dist-packages/repolib
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/command/add.py to add.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/command/argparser.py to argparser.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/command/command.py to command.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/command/__init__.py to __init__.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/deb.py to deb.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/system_test.py to system_test.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/system.py to system.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/source.py to source.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/__version__.py to __version__.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/util.py to util.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/legacy_deb_test.py to legacy_deb_test.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/ppa.py to ppa.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/legacy_deb.py to legacy_deb.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/source_test.py to source_test.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/deb_test.py to deb_test.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/ppa_test.py to ppa_test.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/dist-packages/repolib/__init__.py to __init__.cpython-310.pyc
running install_scripts
copying build/scripts-3.10/apt-manage -> /usr/local/bin
changing mode of /usr/local/bin/apt-manage to 755
running install_data
copying data/apt-manage -> /usr/local/share/bash-completion/completions
running install_egg_info
Writing /usr/local/lib/python3.10/dist-packages/repolib-1.2.0.egg-info

apt-manage -h
usage: apt-manage [-h] COMMAND ...

Manage software sources and repositories

positional arguments:
  COMMAND     ...
    add       Add a new repository to the system.
    remove    Remove a configured repository.
    modify    Change a configured repository.
    list      List configured repositories. If a repository name is provided, show details about
              that repository.
    source    Enable/disable source code packages for repositories

options:
  -h, --help  show this help message and exit

apt-manage version: 1.2.0

apt-manage list
Traceback (most recent call last):
  File "/usr/local/bin/apt-manage", line 90, in <module>
    main()
  File "/usr/local/bin/apt-manage", line 86, in main
    action[args.action](log, args, parser)
KeyError: 'list'

apt list --installed
Listing... Done

python-apt-common/jammy-updates,now 2.3.0ubuntu2.1 all [installed,automatic]
python-babel-localedata/jammy,now 2.8.0+dfsg.1-7 all [installed,automatic]
python3-acme/jammy,now 1.21.0-1 all [installed,automatic]
python3-all/jammy-updates,now 3.10.6-1~22.04 amd64 [installed]
python3-apport/jammy-updates,now 2.20.11-0ubuntu82.3 all [installed,automatic]
python3-apt/jammy-updates,now 2.3.0ubuntu2.1 amd64 [installed,automatic]
python3-attr/jammy,now 21.2.0-1 all [installed,automatic]
python3-augeas/jammy,now 0.5.0-1.1 all [installed,automatic]
python3-automat/jammy,now 20.2.0-1 all [installed,automatic]
python3-babel/jammy,now 2.8.0+dfsg.1-7 all [installed,automatic]
python3-bcrypt/jammy,now 3.2.0-1build1 amd64 [installed,automatic]
python3-blinker/jammy,now 1.4+dfsg1-0.4 all [installed,automatic]
python3-certbot-apache/jammy,now 1.21.0-1 all [installed]
python3-certbot/jammy,now 1.21.0-1build1 all [installed,automatic]
python3-certifi/jammy,now 2020.6.20-1 all [installed,automatic]
python3-cffi-backend/jammy,now 1.15.0-1build2 amd64 [installed,automatic]
python3-chardet/jammy,now 4.0.0-1 all [installed,automatic]
python3-click/jammy,now 8.0.3-1 all [installed,automatic]
python3-colorama/jammy,now 0.4.4-1 all [installed,automatic]
python3-commandnotfound/jammy,now 22.04.0 all [installed,automatic]
python3-configargparse/jammy,now 1.5.3-1 all [installed,automatic]
python3-configobj/jammy,now 5.0.6-5 all [installed,automatic]
python3-constantly/jammy,now 15.1.0-2 all [installed,automatic]
python3-cryptography/jammy,now 3.4.8-1ubuntu2 amd64 [installed,automatic]
python3-dbus/jammy,now 1.2.18-3build1 amd64 [installed,automatic]
python3-debconf/jammy,now 1.5.79ubuntu1 all [installed,automatic]
python3-debian/jammy,now 0.1.43ubuntu1 all [installed,automatic]
python3-dev/jammy-updates,now 3.10.6-1~22.04 amd64 [installed,automatic]
python3-distro-info/jammy,now 1.1build1 all [installed,automatic]
python3-distro/jammy,now 1.7.0-1 all [installed,automatic]
python3-distupgrade/jammy-updates,now 1:22.04.15 all [installed,automatic]
python3-distutils/jammy-updates,now 3.10.6-1~22.04 all [installed]
python3-gdbm/jammy-updates,now 3.10.6-1~22.04 amd64 [installed,automatic]
python3-gi/jammy-updates,now 3.42.1-0ubuntu1 amd64 [installed,automatic]
python3-hamcrest/jammy,now 2.0.2-2 all [installed,automatic]
python3-httplib2/jammy,now 0.20.2-2 all [installed,automatic]
python3-hyperlink/jammy,now 21.0.0-3 all [installed,automatic]
python3-icu/jammy,now 2.8.1-0ubuntu2 amd64 [installed,automatic]
python3-idna/jammy,now 3.3-1 all [installed,automatic]
python3-importlib-metadata/jammy,now 4.6.4-1 all [installed]
python3-incremental/jammy,now 21.3.0-1 all [installed,automatic]
python3-jeepney/jammy,now 0.7.1-3 all [installed,automatic]
python3-jinja2/jammy,now 3.0.3-1 all [installed]
python3-josepy/jammy,now 1.10.0-1 all [installed,automatic]
python3-json-pointer/jammy,now 2.0-0ubuntu1 all [installed]
python3-jsonpatch/jammy,now 1.32-2 all [installed]
python3-jsonschema/jammy,now 3.2.0-0ubuntu2 all [installed]
python3-jwt/jammy-updates,jammy-security,now 2.3.0-1ubuntu0.2 all [installed,automatic]
python3-keyring/jammy,now 23.5.0-1 all [installed,automatic]
python3-launchpadlib/jammy,now 1.10.16-1 all [installed,automatic]
python3-lazr.restfulclient/jammy,now 0.14.4-1 all [installed,automatic]
python3-lazr.uri/jammy,now 1.0.6-2 all [installed,automatic]
python3-lib2to3/jammy-updates,now 3.10.6-1~22.04 all [installed]
python3-magic/jammy,now 2:0.4.24-2 all [installed,automatic]
python3-markupsafe/jammy,now 2.0.1-2build1 amd64 [installed]
python3-minimal/jammy-updates,now 3.10.6-1~22.04 amd64 [installed,automatic]
python3-more-itertools/jammy,now 8.10.0-2 all [installed]
python3-nacl/jammy,now 1.5.0-2 amd64 [installed]
python3-netifaces/jammy,now 0.11.0-1build2 amd64 [installed,automatic]
python3-newt/jammy,now 0.52.21-5ubuntu2 amd64 [installed,automatic]
python3-oauthlib/jammy-updates,jammy-security,now 3.2.0-1ubuntu0.1 all [installed,automatic]
python3-openssl/jammy,now 21.0.0-1 all [installed,automatic]
python3-parsedatetime/jammy,now 2.6-2 all [installed,automatic]
python3-pcp/jammy,now 5.3.6-1build1 amd64 [installed,automatic]
python3-pexpect/jammy,now 4.8.0-2ubuntu1 all [installed,automatic]
python3-pip/jammy,now 22.0.2+dfsg-1 all [installed]
python3-pkg-resources/jammy,now 59.6.0-1.2 all [installed,automatic]
python3-problem-report/jammy-updates,now 2.20.11-0ubuntu82.3 all [installed,automatic]
python3-ptyprocess/jammy,now 0.7.0-3 all [installed,automatic]
python3-pyasn1-modules/jammy,now 0.2.1-1 all [installed,automatic]
python3-pyasn1/jammy,now 0.4.8-1 all [installed,automatic]
python3-pyinotify/jammy,now 0.9.6-1.3 all [installed,automatic]
python3-pymacaroons/jammy,now 0.13.0-4 all [installed]
python3-pyparsing/jammy,now 2.4.7-1 all [installed,automatic]
python3-pyrsistent/jammy,now 0.18.1-1build1 amd64 [installed]
python3-requests-toolbelt/jammy,now 0.9.1-1 all [installed,automatic]
python3-requests/jammy,now 2.25.1+dfsg-2 all [installed,automatic]
python3-rfc3339/jammy,now 1.1-3 all [installed,automatic]
python3-secretstorage/jammy,now 3.3.1-1 all [installed,automatic]
python3-serial/jammy,now 3.5-1 all [installed]
python3-service-identity/jammy,now 18.1.0-6 all [installed,automatic]
python3-setuptools/jammy,now 59.6.0-1.2 all [installed]
python3-six/jammy,now 1.16.0-3ubuntu1 all [installed,automatic]
python3-software-properties/jammy-updates,now 0.99.22.3 all [installed,automatic]
python3-systemd/jammy,now 234-3ubuntu2 amd64 [installed,automatic]
python3-twisted/jammy-updates,jammy-security,now 22.1.0-2ubuntu2.3 all [installed,automatic]
python3-tz/jammy-updates,now 2022.1-1ubuntu0.22.04.0 all [installed,automatic]
python3-update-manager/jammy,now 1:22.04.9 all [installed,upgradable to: 1:22.04.10]
python3-urllib3/jammy,now 1.26.5-1~exp1 all [installed,automatic]
python3-wadllib/jammy,now 1.3.6-1 all [installed,automatic]
python3-wheel/jammy,now 0.37.1-2 all [installed,automatic]
python3-yaml/jammy,now 5.4.1-1ubuntu1 amd64 [installed,automatic]
python3-zipp/jammy,now 1.0.0-3 all [installed]
python3-zope.component/jammy,now 4.3.0-3 all [installed,automatic]
python3-zope.event/jammy,now 4.4-3 all [installed,automatic]
python3-zope.hookable/jammy,now 5.1.0-1build1 amd64 [installed,automatic]
python3-zope.interface/jammy,now 5.4.0-1build1 amd64 [installed,automatic]
python3.10-dev/jammy-updates,jammy-security,now 3.10.6-1~22.04.2 amd64 [installed,automatic]
python3.10-minimal/jammy-updates,jammy-security,now 3.10.6-1~22.04.2 amd64 [installed,automatic]
python3.10/jammy-updates,jammy-security,now 3.10.6-1~22.04.2 amd64 [installed,automatic]
python3/jammy-updates,now 3.10.6-1~22.04 amd64 [installed,automatic]

apt-key list
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2021-06-22 [SC] [expires: 2031-06-20]
      84FA A998 3B24 AEF2 4D6C  87F1 FEBB 7D18 1257 6482
uid           [ unknown] CISOfy software signing <software@cisofy.com>
sub   rsa4096 2021-06-22 [S] [expires: 2031-06-20]
sub   rsa4096 2021-06-22 [E] [expires: 2031-06-20]

pub   rsa2048 2013-11-27 [SC]
      6CCE A47B 2281 732D F5D5  04D0 0C54 D189 F4BA 284D
uid           [ unknown] Collabora Productivity <libreoffice@collabora.com>
uid           [ unknown] LibreOffice-from-Collabora <support@libreoffice.collabora.com>
uid           [ unknown] Collabora LibreOffice <support@libreoffice.collabora.com>

pub   rsa2048 2016-02-17 [SC]
      9FE3 B226 BD77 5196 D8C2  E599 DE88 104A A4C6 383F
uid           [ unknown] DigitalOcean Insights Engineering <sonar-agent@digitalocean.com>
sub   rsa2048 2016-02-17 [E]

pub   rsa4096 2022-11-09 [SC]
      902C 44B4 2EA9 A17F 8578  5109 77B7 9B3F FAF7 EF65
uid           [ unknown] DigitalOcean Insights Engineering <sonar-agent@digitalocean.com>

/etc/apt/trusted.gpg.d/ondrej_ubuntu_apache2.gpg
------------------------------------------------
pub   rsa1024 2009-01-26 [SC]
      14AA 40EC 0831 7567 56D7  F66C 4F4E A0AA E526 7A6C
uid           [ unknown] Launchpad PPA for Ondřej Surý

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
------------------------------------------------------
pub   rsa4096 2018-09-17 [SC]
      F6EC B376 2474 EDA9 D21B  7022 8719 20D1 991B C93C
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>

~# apt-manage list ondrej_ubuntu_apache2.gpg
Traceback (most recent call last):
  File "/usr/local/bin/apt-manage", line 90, in <module>
    main()
  File "/usr/local/bin/apt-manage", line 86, in main
    action[args.action](log, args, parser)
KeyError: 'list'

**Comment by isantop** [comment]
Are you having issues with `apt-manage` failing to start every time you run any commands?

If so, please post the output from `apt-manage -bb list` and I can check what's going on.

As a note: please ensure that bug reports include a normal description of the problem. Dumping full terminal output from several commands doesn't help because it doesn't provide any context behind the issue you're experiencing.
