### ISSUE TITLE
Quick install script or 'more complete' installation details

### ISSUE THREAD

**Issue by Lockszmith-GH** [pop-os/repolib#69]
I have [an answer in askubunu](https://askubuntu.com/a/1412554/720005) which is based on my success of installing apt-manage on Debian and Ubuntu systems in varied situations.

I think something more detailed about how to install would be a good thing to maintain in the project.
Maybe even a 'quick-install' script that can be invoked with curl.

Would the mintainers be open to such a PR?

**Comment by leviport** [comment]
Certainly! We love community involvement, and that sounds like it would be a great addition.

**Comment by Lockszmith-GH** [comment]
Awesome, can you point me at the right place to add something like this?

**Comment by leviport** [comment]
For instructions, probably the README. Not sure about the script. I think PyPi is intended to fill that role.

**Comment by Lockszmith-GH** [comment]
OK, I'll start a PR, and get the feedback there.

**Comment by Lockszmith-GH** [comment]
Should have closed this long ago, when the PR was merged.
