### ISSUE TITLE
Remove ppa:teward/znc from repolib docs/examples

### ISSUE THREAD

**Issue by teward** [pop-os/repolib#72]
It has come to my attention through various sources that my ZNC repository I haven't updated in a long eternity is in your documentation as an example of a 'disabled' repository in the deb822 formatting documentation.

In Launchpad, that PPA is disabled, does not publish, and is actually scheduled for deletion on the PPA system because I am not maintaining it anymore.

To that end, you might want to use a different example for your repos.  Disabled or not, it isn't necessarily a positive to be using old/obsolete links in documentation.

**Comment by leviport** [comment]
Thank you for bringing this to our attention. Which documentation are you referring to?

**Comment by teward** [comment]
https://repolib.readthedocs.io/en/latest/deb822-format.html is currently using ppa:teward/znc on Launchpad as an example of a Disabled entry.  Disabled or not, if the URL explodes it might cause your documentation to be "Wait, this is a dead link, what're you doing!"
